name: CI/CD Pipeline

on:
  push:
    branches:
      - Dockerisation
  pull_request:
    branches:
      - Dockerisation

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: 'gcr.io/cloud-builders/docker'
        args:
          - 'build'
          - '-t'
          - 'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}'
          - '.'

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t myapp .
          docker tag myapp:latest <your-docker-registry>/myapp:latest
          docker push <your-docker-registry>/myapp:latest

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: <your-project-id>
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy myapp \
            --image=<your-docker-registry>/myapp:latest \
            --platform=managed \
            --region=<your-region> \
            --allow-unauthenticated
