name: CI/CD Pipeline

on:
  push:
    branches:
      - Dockerisation
  pull_request:
    branches:
      - Dockerisation

env:
  ACTIONS_RUNNER_DEBUG: true
  PROJECT_ID: hellowolrdproject-387922
  _ARTIFACT_REGISTRY_REPO: hello-world-project-gcl-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure gcloud credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_AUTH_TOKEN }}

      - name: Setup gcloud / gsutil
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCS_PROJECT }}

      - name: Display gcloud auth list
        run: |
          gcloud auth list --format="yaml"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and push container image
        run: |
          gcloud builds submit --tag=gcr.io/${{ env.PROJECT_ID }}/${{ env._ARTIFACT_REGISTRY_REPO }}/myimage:${{ github.sha }} .